// <auto-generated />
using System;
using Backend_AgendaProApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_AgendaProApi.Infrastructure.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    [Migration("20260305020835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.BloqueHorario", b =>
                {
                    b.Property<int>("IdBloqueHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBloqueHorario"));

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdHorarios")
                        .HasColumnType("int");

                    b.HasKey("IdBloqueHorario");

                    b.HasIndex("IdHorarios");

                    b.ToTable("BloquesHorario", (string)null);
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Cita", b =>
                {
                    b.Property<int>("IdCitas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCitas"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBloqueHorario")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdCitas");

                    b.HasIndex("IdBloqueHorario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Citas", (string)null);
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Especialista", b =>
                {
                    b.Property<int>("IdEspecialista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialista"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdEspecialista");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Especialista", (string)null);
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Horario", b =>
                {
                    b.Property<int>("IdHorarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorarios"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdEspecialista")
                        .HasColumnType("int");

                    b.HasKey("IdHorarios");

                    b.HasIndex("IdEspecialista");

                    b.ToTable("Horarios", (string)null);
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.BloqueHorario", b =>
                {
                    b.HasOne("Backend_AgendaProApi.Domain.Entities.Horario", "Horario")
                        .WithMany("BloquesHorario")
                        .HasForeignKey("IdHorarios")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Cita", b =>
                {
                    b.HasOne("Backend_AgendaProApi.Domain.Entities.BloqueHorario", "BloqueHorario")
                        .WithMany("Citas")
                        .HasForeignKey("IdBloqueHorario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_AgendaProApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Citas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloqueHorario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Horario", b =>
                {
                    b.HasOne("Backend_AgendaProApi.Domain.Entities.Especialista", "Especialista")
                        .WithMany("Horarios")
                        .HasForeignKey("IdEspecialista")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialista");
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Backend_AgendaProApi.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.BloqueHorario", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Especialista", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Horario", b =>
                {
                    b.Navigation("BloquesHorario");
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Backend_AgendaProApi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
