name: Build and deploy ASP.Net Core app to Azure Web App - web-desarrollosoftware-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Backend-AgendaProApi.Api/Backend-AgendaProApi.Api.csproj

      - name: Build
        run: dotnet build Backend-AgendaProApi.Api/Backend-AgendaProApi.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Backend-AgendaProApi.Api/Backend-AgendaProApi.Api.csproj --configuration Release --no-build --output ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8FEC478F31994FCABCC4F3F139D54840 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_56FD0AAA92FA484BBD05E3B2CDCF8BCE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_734A70CB0B3F42B6A3D13B7A2975BD64 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'web-desarrollosoftware-api'
          slot-name: 'Production'
          package: ./publish